export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FINISHED_MATCHES_START = "FINISHED_MATCHES_START";
export const FINISHED_MATCHES_ACK = "FINISHED_MATCHES_ACK";
export const FINISHED_MATCHES_ERROR = "FINISHED_MATCHES_ERROR";

export const INCOMING_MATCHES_START = "INCOMING_MATCHES_START";
export const INCOMING_MATCHES_ACK = "INCOMING_MATCHES_ACK";
export const INCOMING_MATCHES_ERROR = "INCOMING_MATCHES_ERROR";

export const AUTH_START = "AUTH_START";
export const AUTH_ACK = "AUTH_ACK";
export const AUTH_NACK = "AUTH_NACK";
export const AUTH_ERROR = "AUTH_ERROR";

export const SIGNUP_TOURNAMENT_START = "SIGNUP_TOURNAMENT_START";
export const SIGNUP_TOURNAMENT_ACK = "SIGNUP_TOURNAMENT_ACK";
export const SIGNUP_TOURNAMENT_ERROR = "SIGNUP_TOURNAMENT_ERROR";