export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FINISHED_MATCHES_START = "FINISHED_MATCHES_START";
export const FINISHED_MATCHES_ACK = "FINISHED_MATCHES_ACK";
export const FINISHED_MATCHES_ERROR = "FINISHED_MATCHES_ERROR";

export const INCOMING_MATCHES_START = "INCOMING_MATCHES_START";
export const INCOMING_MATCHES_ACK = "INCOMING_MATCHES_ACK";
export const INCOMING_MATCHES_ERROR = "INCOMING_MATCHES_ERROR";

export const AUTH_START = "AUTH_START";
export const AUTH_ACK = "AUTH_ACK";
export const AUTH_NACK = "AUTH_NACK";
export const AUTH_ERROR = "AUTH_ERROR";

export const SIGNUP_TOURNAMENT_START = "SIGNUP_TOURNAMENT_START";
export const SIGNUP_TOURNAMENT_ACK = "SIGNUP_TOURNAMENT_ACK";
export const SIGNUP_TOURNAMENT_ERROR = "SIGNUP_TOURNAMENT_ERROR";

export const FETCH_SIGNUPABLE_TOURNAMENT_START = "FETCH_SIGNUPABLE_TOURNAMENT_START";
export const FETCH_SIGNUPABLE_TOURNAMENT_ACK = "FETCH_SIGNUPABLE_TOURNAMENT_ACK";
export const FETCH_SIGNUPABLE_TOURNAMENT_ERROR = "FETCH_SIGNUPABLE_TOURNAMENT_ERROR";

export const FINISHED_BETTABLE_START = "FINISHED_BETTABLE_START";
export const FINISHED_BETTABLE_ACK = "FINISHED_BETTABLE_ACK";
export const FINISHED_BETTABLE_ERROR = "FINISHED_BETTABLE_ERROR";


export const POST_BET_START = "POST_BET_START";
export const POST_BET_ACK = "POST_BET_ACK";
export const POST_BET_ERROR = "POST_BET_ERROR";

export const DELETE_BET_START = "DELETE_BET_START";
export const DELETE_BET_ACK = "DELETE_BET_ACK";
export const DELETE_BET_ERROR = "DELETE_BET_ERROR";

export const FETCH_DETAILS_START = "FETCH_DETAILS_START";
export const FETCH_DETAILS_ACK = "FETCH_DETAILS_ACK";
export const FETCH_DETAILS_ERROR = "FETCH_DETAILS_ERROR";

export const FETCH_HISTORY_START = "FETCH_HISTORY_START";
export const FETCH_HISTORY_ACK = "FETCH_HISTORY_ACK";
export const FETCH_HISTORY_ERROR = "FETCH_HISTORY_ERROR";